AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'exe/**'
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['\#.*'] # ignore long comments

Metrics/MethodLength:
  Max: 20

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false